name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

template: |
  ## What’s Changed
  This is a test test with a bit of text and more

  $CHANGES

  ## Contributers

  $CONTRIBUTORS
